services:
  
  checkout-write-service:
    build:
      context: ./write-side
      dockerfile: Dockerfile
    container_name: checkout-write
    ports:
      - "3000:3000"
    restart: always
    networks:
      - checkout-service-network

  
  checkout-read-service:
    build:
      context: ./read-side
      dockerfile: Dockerfile
    container_name: checkout-read
    ports:
      - "3001:3001"
    restart: always
    networks:
      - checkout-service-network


networks:
  checkout-service-network: